### ISSUE TITLE
Use version with Node 16

### ISSUE THREAD

**Issue by frankvollebregt** [Fooji/create-aws-profile-action#7]
Hi! Thank you for this useful action. When trying to resolve some warnings during my workflow runs, I was upgrading my various actions to their latest versions to make sure they supported node v16. I can see that this action has already been upgraded in the `master` branch (https://github.com/Fooji/create-aws-profile-action/pull/5), but in the marketplace it still seems to refer to the old version.

I'm not too familiar with how GH Actions work in this regard. If I refer to the specific commit hash or branch within this repository, the action runs without any issues, but if I just specify `@v2` it seems to default to an older version (supposedly the first version that set the version tag to `v2`).

Can you release this upgraded version as a `v2.1` or `v3` to the marketplace? Then I'll be able to just include a version number, instead of specifying the github branch/commit.

**Comment by klems** [comment]
+1 Yeah that would be nice, thanks in advance :)

**Comment by dkershner6** [comment]
This has been forked and updated to Node 20 here, if interested: https://github.com/marketplace/actions/create-aws-profile-action

**Comment by frankvollebregt** [comment]
@dkershner6 I'm in doubt whether to use your fork now, or keep using this version (which has received a marketplace update as per https://github.com/Fooji/create-aws-profile-action/pull/8).

As it is still in active use within the Fooji organization, I assume this will be kept up-to-date, so I'll keep using this version.

I guess this is always the trade-off with reliance on other peoples'  software, you never know how long term support will turn out to be 😄

**Comment by dkershner6** [comment]
> @dkershner6 I'm in doubt whether to use your fork now, or keep using this version (which has received a marketplace update as per #8).
> 
> As it is still in active use within the Fooji organization, I assume this will be kept up-to-date, so I'll keep using this version.
> 
> I guess this is always the trade-off with reliance on other peoples' software, you never know how long term support will turn out to be 😄

Totally.  We are using this in our org as well and since we already have many actions, this wasn't a big add.  It'll be here if you ever need it.
